blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/bloodynite/lazyredis/discussions
    about: Ask questions or share ideas outside of bug reports and feature requests
